name: npm Publish dev

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: 'https://registry.npmjs.org'

            - name: Setup pnpm 8.6.0
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.6.0
                  run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --prefer-offline --frozen-lockfile

            - name: Build
              run: pnpm run build
            - uses: actions/upload-artifact@v3
              with:
                  name: build-output
                  path: dist
                  if-no-files-found: error
            - run: pnpm size
            - uses: martinbeentjes/npm-get-version-action@v1.3.1
              id: package-version
            - run:
                  pnpm version --no-git-tag-version --new-version ${{steps.package-version.outputs.current-version }}-dev.${{github.sha }}
                  # npm install -g npm@latest is necessary to make provenance available (available since v9.6.5 or so). More info: https://docs.npmjs.com/generating-provenance-statements
            - run: npm install -g npm@latest
            - run: npm publish --access public --tag dev
              env:
                  # Is connected with actions/setup-node -> registry-url
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
