name: npm Publish dev

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                version: 7.9.2
            - uses: actions/setup-node@v3
              with:
                cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install --prefer-offline --frozen-lockfile
            - name: Build
              run: pnpm run build
            - uses: actions/upload-artifact@v3
              with:
                  name: build-output
                  path: dist
                  if-no-files-found: error
            - run: pnpm run size
            - uses: martinbeentjes/npm-get-version-action@v1.3.1
              id: package-version
            - run: pnpm run version --no-git-tag-version --new-version ${{ steps.package-version.outputs.current-version }}-dev.${{ github.sha }}
              # npm install -g npm@latest is necessary to make provenance available (available since v9.6.5 or so). More info: https://docs.npmjs.com/generating-provenance-statements
            - run: npm install -g npm@latest
            - run: npm publish --access public --tag dev
              env:
                  # Is connected with actions/setup-node -> registry-url
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
